### ISSUE TITLE
Couldn't establish a connection "ws://ip:3000/ws/4D196AF40E36C8ECC980221E60AB291F". Is your browser running?

### ISSUE THREAD

**Issue by KONEV5** [malte843/rsg-socialclub-api#1]
when i open http://ip:3000/?targetId=4D196AF40E36C8ECC980221E60AB291F，My Page is ：Couldn't establish a connection "ws://ip:3000/ws/4D196AF40E36C8ECC980221E60AB291F". Is your browser running?。   How should I deal with it

**Comment by malte843** [comment]
do you have a log

**Comment by malte843** [comment]
looks like puppeteer had an update and it doesnt work with the new one. Try now with new package.json and make sure to reinstall modules before

**Comment by KONEV5** [comment]
info: [12:41:38 PM] [INFO] => Starting...
info: [12:41:38 PM] [INFO] => Alive on Port: 4000
info: [12:41:39 PM] [DEBUG] => Navigating to https://socialclub.rockstargames.com/
info: [12:41:49 PM] [DEBUG] => Loaded Page
error: [12:41:49 PM] [ERROR] => Error getting bearer, starting login.
TypeError: Cannot read properties of undefined (reading 'value')
error: [12:41:49 PM] [ERROR] => Error getting bearer, starting login.
TypeError: Cannot read properties of undefined (reading 'value')
info: [12:41:49 PM] [DEBUG] => Started login process...
info: [12:41:49 PM] [DEBUG] => Trying to start browser...
info: [12:41:50 PM] [DEBUG] => Started browser...
info: [12:41:50 PM] [DEBUG] => Started new tab...
info: [12:41:50 PM] [DEBUG] => Navigating to https://signin.rockstargames.com/signin/user-form?cid=socialclub
info: [12:41:58 PM] [DEBUG] => Loaded Page
info: [12:41:58 PM] [INFO] => Started portal on: http://127.0.0.1:3000/?targetId=F04C24297BCF256F87C634FA2AD459B1
info: [12:41:58 PM] [INFO] => Login with your socialclub credentials and dont forget to tick remember me box
info: [12:41:58 PM] [INFO] => Restart the app when you're done.

###  Sorry, the page still won't open

**Comment by malte843** [comment]
completely wont open or like before the error

**Comment by KONEV5** [comment]
har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

I deleted package-lock.json, `npm install`
